{% set name = "pypsrp" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypsrp-{{ version }}.tar.gz
  sha256: f5500acd11dfe742d51b7fbb61321ba721038a300d67763dc52babe709db65e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cryptography
    - pyspnego <1.0.0
    - requests >=2.9.1

test:
  imports:
    - pypsrp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jborean93/pypsrp
  summary: PowerShell Remoting Protocol and WinRM for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/jborean93/pypsrp
  doc_url: https://github.com/jborean93/pypsrp

extra:
  recipe-maintainers:
    - xylar
